server:
  port: 8888

spring:
  #  profiles:
  #    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
#        native:
#          search-locations: file:////Users/greencar/repo/github/spring-cloud-gateway-study
        git: #default
          uri: https://github.com/neodio/spring-cloud-config-study
          default-label: main
        #          username: <github-id>
        #          password: <gihub-accessToken>
        bootstrap: true

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics