global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'user-service'
    metrics_path: '/user-service/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'localhost:8000' ]

  - job_name: 'order-service'
    metrics_path: '/order-service/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'localhost:8000' ]